//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteHotel.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int MaHD { get; set; }
        public string MaPhong { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Room Room { get; set; }
    }
}
