//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteHotel.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public string MaPhong { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<decimal> GiaPhong { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> MaDV { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DichVu DichVu { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
